### ISSUE TITLE
Logo in Footer?

### ISSUE THREAD

**Issue by dbloom** [ranges-network/ranges-network.github.io#5]
@peterdesmet 

Today's challenge:

Is there any way to add a logo to the footer? I've tried several different strategies all of which resulted in errors that the "mapping values are not allowed" - and that's mostly what I expected.

I need to find a way to put the NSF logo in the footer since the project is funded by them. Was hoping to add a third column so that the logo could live in the middle of the footer (column 2).

If it's not possible, I'll find some other way to recognize NSF, such as putting a line of text with the logo at the bottom of each page so it will appear just above the footer. That's not a bad option.

Thanks for you help with all of this.

**Comment by dbloom** [comment]
Related, but different.

Is it possible to add an image to the background in the team and participants ymls?

**Comment by peterdesmet** [comment]
The footer isn't designed for images, but it is possible to add them to any of the elements that accepts Markdown. In the footer that is the `columns > description` and the `license`. You can't add images to any of the `text`/`href` elements.

The best option I found is to do it like so:

![Ranges-Participants-and-Partners-Ranges (1)](https://github.com/ranges-network/ranges-network.github.io/assets/600993/f403630f-31b8-4607-8e2a-19511562f5c5)

```yaml
# Columns
columns:
  - description: >
      ![NSF](/assets/images/nsflogos/NSF-Symbol.png){:.w-75}
  - description: Project Partners
    links:
    - text: FuTRES
```

1. It's added to it's own 3rd column.
2. The URL needs to start with `/` so it always looks from the root of the website and not from the page it is currently displayed at.
3. You need to add `{:.w-75}` to [style](https://peterdesmet.com/petridish/docs/markdown/#styling-content) the image. `w-75` is a Bootstrap class that will display the images at 75% of the available width (here the width of the column). If you don't add it, the image will be displayed at full resolution.
4. It is also possible to _link_ the image to the NSF, like so:

```yaml
# Columns
columns:
  - description: >
      [![NSF](/assets/images/nsflogos/NSF-Symbol.png){:.w-75}](https://www.nsf.org/){:target="_blank"}
  - description: Project Partners
```
