### ISSUE TITLE
Is it possible to add image to team members

### ISSUE THREAD

**Issue by peterdesmet** [ranges-network/ranges-network.github.io#6]
Is it possible to add an image to the background in the team and participants ymls?

_Originally posted by @dbloom in https://github.com/ranges-network/ranges-network.github.io/issues/5#issuecomment-1786257194_

**Comment by peterdesmet** [comment]
Created a separate issue for this. How do you mean to the background?

1. To the banner of the page?
2. To the `description` of each participants?

I notice you use [participants](https://ranges-network.github.io/participants/) to list the institutions as members, and then use the `description` to include the people. That will only give you limited options.

**Comment by dbloom** [comment]
Yes, I'm quite happy to keep the limited options for now. If the time comes for a full page filled with all the institutional glory people can imagine, then I'll use a different page template.

I would like to add an image to banner, rather than just a yellowish band of color, behind the "Ranges Participants and Projects" title.

**Comment by peterdesmet** [comment]
To add a banner image, add a `background` in the yaml front matter (the metadata at the top) of participants.md (not particants.yml, that is just the data that is fed to the page). Instructions here: http://peterdesmet.com/petridish/docs/configuration/#pages

**Comment by peterdesmet** [comment]
Also note that the `description` in participants.yml accepts Markdown, so you could list the members for each institution as an unnumbered list:

```yml
- name: University of Nevada, Reno, Museum of Natural History
  image: assets/images/participantlogos/UNRLogo_SMALL.png # Can be external link
  description: |
    - PI: [Chris Feldman](https://feldmanlab.weebly.com/)
    - CoPI: [Julie Allen](https://www.biol.vt.edu/People/Faculty.html)
```

Note the use of `|` which tells Jekyll the keep linebreaks in what follows (while `>` ignores linebreaks)

Result:
<img width="673" alt="Screenshot 2023-10-31 at 21 55 12" src="https://github.com/ranges-network/ranges-network.github.io/assets/600993/1816e615-def4-48d0-bc63-e367c103d549">
